// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lchbhoembbsjmulhifuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjaGJob2VtYmJzam11bGhpZnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTk3NTcsImV4cCI6MjA2MTQzNTc1N30.dvjv0qgp5ZZI3_0TMn8AkcA9nhcmoNnpb3ljqEwN7yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);